services:
  - type: web
    name: a-store
    env: docker
    dockerfilePath: ./Dockerfile.prod
    plan: free
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /_health
    disk:
      name: a-store-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 18.16
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: a-store
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: a-store
    plan: starter
